audio-chunk: 8000 #audio data to send (size in bytes)
audio-rate: 44100
channels: 1 # Watson doesn't support yet 2 channel, let it to 1
watson-stt:
  user: user-uuid
  password: passs
  model: en-US_BroadbandModel
  tokenauth: ~
