watson-stt:
  user: dfd80521-573d-489d-bade-d6efe4c133b5
  password: Il60FdAmJX7o
  model: en-US_BroadbandModel
  fileInput: ./recordings.txt
  dirOutput: ./output
  contentType: audio/wav
  threads: 1
  tokenauth: ~
